version: '3.3'

volumes:
  static:
  media:

services:

  web:
    image: pashvd/economic-game:latest
    restart: always
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - static:/code/static/
      - media:/code/media/

  nginx:
    image: nginx:1.19.3
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static:/code/static/
      - media:/code/media/
    depends_on:
      - web
    ports:
      - 8008:8008

  redis:
    image: redis:alpine
  celery:
    restart: always
    build: .
    command: >
      bash -c "celery -A EconomicGame worker -l info && 
               celery -A EconomicGame beat -l info &&
               celery -A EconomicGame flower --port=5555"
    volumes:
      - static:/code/static/
      - media:/code/media/
    depends_on:
      - redis
      - web
